export const PROJECT_ID = 'farcaster-frames-template';
export const PROJECT_TITLE = "Degen Hat Snake";
export const PROJECT_DESCRIPTION = "Hunt for degen hats in this snake game";
export const GITHUB_URL = "https://github.com/farcasterxyz/protocol";
export const DOCS_URL = "https://docs.farcaster.xyz/developers/";
export const DEGEN_TIPS_URL = "https://www.degen.tips";
export const LIVES_PER_DAY = 3;
export const USDC_ADDRESS = '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913';
export const RECIPIENT_ADDRESS = '0x6B512f25976a164c922Cb4f3EcDBB02E223eA445';
